
name: Sync GitHub Stars To Notion

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  runScripts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      
      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Script To Sync GitHub Stars To Notion
        run: python sync_star_to_notion.py
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
