name: Random Walks With Notion

on:
  workflow_dispatch:
  schedule:
    - cron: "30 17 * * *"

jobs:
  runScripts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Script To Pick Data From Notion
        run: python random_walk_with_notion.py
        env:
          NOTION_PAGE: ${{ secrets.NOTION_STAR_PAGE }}
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          WECHAT_CORP_ID: ${{ secrets.WECHAT_CORP_ID }}
          WECHAT_CORP_SECRET: ${{ secrets.WECHAT_NOTIFYER_SECRET }}
          WECHAT_AGENT_ID: ${{ secrets.WECHAT_NOTIFYER_AGENT_ID }}
          WECHAT_TO_USER: ${{ secrets.WECHAT_NOTIFYER_USER }}
          WECHAT_MEDIA_ID: ${{ secrets.WECHAT_NOTIFYER_MEDIA_ID }}
